name: pupil
github: https://www.github.com/essanpupil
about: Programmer yang tahu beberapa hal.
urls:
    - text: github
      url: https://github.com/essanpupil
    - text: twitter
      url: https://twitter.com/essanpupil
    - text: linkedin
      url: https://id.linkedin.com/in/essanpupil
gems: [jekyll-gist]
