# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pupil >> Ikhsan Noor Rosyidin
email: jakethitam1985@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Catatan Programmer</h1>Semoga yang tertulis disini bermanfaat bagi teman-teman pembaca."



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pupil.id" # the base hostname & protocol for your site
twitter_username: essanpupil
github_username:  essanpupil

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal